name: "Deploy package"

on:
  push:
    # Deploy only when the commit ends with NEXT
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/goldenm-software/python-builder:3.11
      options: --user root
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Build
        run: |
          pip install --upgrade pip build twine
          python3 -m build
        
      - name: Upload to Python Package Index
        uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
        with:
          user: ${{ secrets.LAYRZ_PYPI_USERNAME }}
          password: ${{ secrets.LAYRZ_PYPI_PASSWORD }}
