name: "Deploy package"

on:
  push:
    # Deploy only when the commit ends with NEXT
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/goldenm-software/python-builder:3.11
      options: --user root
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    env:
      TWINE_PASSWORD: ${{ secrets.LAYRZ_PYPI_TOKEN }}
      TWINE_USERNAME: ${{ secrets.LAYRZ_PYPI_USERNAME }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Build
        run: |
          pip install --upgrade pip build twine
          python3 -m build
        
      - name: Upload to Python Package Index
        run: TWINE_PASSWORD=${PYPI_PASSWORD} TWINE_USERNAME=${PYPI_USERNAME} python3 -m twine upload dist/*
